version: '3.8'

services:
  app:
    build: .
    container_name: bagisto_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./database:/var/www/html/database
    networks:
      - bagisto-network
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bagisto
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_DATABASE_TEST=/var/www/html/database/testing.sqlite
    command: bash -c "sleep 10 && composer install && php artisan key:generate && php-fpm"
    platform: linux/arm64

  db:
    image: mysql:5.7
    container_name: bagisto_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bagisto
      MYSQL_PASSWORD: secret
      MYSQL_USER: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bagisto-network
    ports:
      - "3306:3306"
    platform: linux/amd64

  nginx:
    image: nginx:alpine
    container_name: bagisto_nginx
    working_dir: /var/www/html
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - bagisto-network
    platform: linux/arm64

networks:
  bagisto-network:
    driver: bridge

volumes:
  db_data:
    driver: local
