name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup PHP (バージョンを8.1に変更)
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'  
          extensions: mbstring, xml, bcmath, sqlite3

      # Copy .env.testing to .env in the src directory
      - name: Copy .env.testing
        run: cp src/.env.testing src/.env

      # Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist
        working-directory: ./src 

      # Generate application key
      - name: Generate key
        run: php artisan key:generate
        working-directory: ./src

      # Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ./src 

      # Create SQLite database
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
        working-directory: ./src 

      # Run tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
        working-directory: ./src
