name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      # Setup PHP (バージョンを8.1に変更)
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'  
          extensions: mbstring, xml, bcmath, pdo, pdo_mysql

      # Copy .env.testing to .env in the src directory
      - name: Copy .env.testing
        run: cp src/.env.testing src/.env

      # Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist
        working-directory: ./src 

      # Generate application key
      - name: Generate key
        run: php artisan key:generate
        working-directory: ./src

      # Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ./src 

      # Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              break
            fi
            sleep 1
          done

      # Run migrations
      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: secret
        run: php artisan migrate --env=testing
        working-directory: ./src 

      # Run tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: secret
        run: php artisan test
        working-directory: ./src
